development:
  adapter: postgresql
  database: bdcg-web-dev
  username: bdcg-web-dev
  password: fishsticks
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: bdcg-web-test
  username: bdcg-web-test
  password: fishsticks
  timeout: 5000
  host: localhost

production:
  adapter: <%= ENV['RDS_DB_ADAPTER'] || 'mysql2' %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  timeout: 5000
